name: deploy-website
# Builds website for PRs/push, but deploys only for push.

# Only run this when the dev branch changes
on:
  push:
    branches: [ dev ]
    paths:
      docs/**  
      
  pull_request:
    branches: [ dev ]
    paths:
      docs/**
      
  workflow_dispatch:


# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt


    # Build the book
    - name: Build the site
      run: |
        sphinx-build docs/ docs/_build/html/

  # Push the book's HTML to github-pages
  deploy-docs:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [ build-docs ]
    steps:

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        keep_files: true
        
